### ISSUE TITLE
HTTP Error 500 on first request after a certain time of inactivity

### ISSUE THREAD

**Issue by cith** [highcharts/highcharts-export-server#40] opened 2016-11-24 07:57 UTC
Hello,

I have made the following observation with the current version (nov 2016) of the export server based on java:

After a certain time of inactivity the export server can't connect to one of the phantomjs instances
and gets a Socket.Timeout.Exception on the first request after the inactivity. 
It seems with the new implementation that through the lifecycle 
a phantomjs instance/process is destroyed beforehand and after the request is made a new phantomjs is newly created.

**Exception:**
[ERROR] --- (SVGConverter.java:requestServer:142) java.net.SocketTimeoutException: Read timed out

**Deployment Details:**
- deployed/tested on Websphere Liberty Profile 16.x or Apache TomEE 7.0.2
- export server (war file) is packaged once again in an ear file 

With the previous version (july 2016) I got no problems.

If you need more details please let me know. 

Thanks in advance.

**Comment by larsac07** [comment] 2017-01-09 15:53
Hi, @cith, sorry for the late reply.

First of all, let me recommend you the new [nodejs-based export server](https://github.com/highcharts/node-export-server), as we are discontinuing development on this software.

As per the issue, I'll have a look and see if I can replicate it. About how much time of inactivity would you say it takes for the timeout to kick in?

**Comment by cith** [comment] 2017-01-10 08:34
Hi,

thanks for your response. I would say the issue occurs after approx. 30+ minutes. It seems that phantomjs instances are being killed and after that period of time on the first try after the inactivity new instances are created which takes too long to get a export result, so the 500 Error is thrown. A intermediate workaround was a retry mechanism (3 trys) in the main application.

I will consider your suggestion for the nodejs-based version, but in the meantime I will keep the old version (july '16 build) because its up and running without any issues.

Thanks in advance.

**Comment by larsac07** [comment] 2017-01-10 11:20
Ok, thank you for the additional information. I'll see what changed and what I can do to avoid the issue

**Comment by larsac07** [comment] 2017-01-10 11:33
Looks like commit ad57103 introduced this. Testing now.

**Comment by larsac07** [comment] 2017-01-10 12:43
I cannot reproduce the issue after 60+ minutes on a Jetty server, trying with WebSphere now

**Comment by larsac07** [comment] 2017-01-10 13:58
I'm sorry, but I cannot reproduce this with WebSphere either, after 60+ minutes. Here's my testing strategy:
1. Start server
2. Export a couple of images
3. Wait at least 60 minutes
4. Export an image

Have you configured any optimization for killing unused subprocesses?

**Comment by cith** [comment] 2017-01-10 15:43
Hi,

no I don't have any optimization configured. Thanks for your time and help. I will investigate the problem further if I got the time. There was also a similar problem posted in the forum but I don't have the link at hand now. If I have any update to the problem I would leave a comment here.

**Comment by larsac07** [comment] 2017-01-27 15:23
Closing this issue for now. Feel free to reopen :)

**Closed by larsac07** 2017-01-27 15:23 UTC
Labels: cannot reproduce
